version: "3.7"

services:
  client:
    build:
      context: ../currency-converter-client/
    ports:
      - "3000:3000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ../currency-converter-client:/usr/client
      - /usr/client/node_modules

  backend:
    build:
      context: ../exchange-api/
    environment:
      FIXER_ACCESS_KEY: "<yourFixerIoAccessKey>"
    ports:
      - "3001:3001"
    volumes:
      - ../exchange-api:/usr/backend
      - /usr/backend/node_modules
